[tool.bumper]
current_version = "0.5.0"

[[tool.bumper.files]]
file = "./pyproject.toml"
search = 'version = "{current_version}"'

[[tool.bumper.files]]
file = "./README.md"
search = "xbmini-py/{current_version}"
